Models/AlooModel.cs
using System.ComponentModel.DataAnnotations;

namespace ASPNETSEMED.Models
{
    public class AlooModel
    {
        [Key]
        public Guid Id {get;set;}

        public required DateTime Criacao {get;set;}

        public required string Escola {get;set;}

        public required string Ip {get;set;}

        public required string Circuito {get;set;}
    }
}



// id	nome	setor	sigla	modelo	ip	status	printpage

Models/AnydeskModel.cs
namespace ASPNETSEMED.Models
{
    public class AnydeskModel
    {
        public string? Id {get;set;}
        public string? Escola {get;set;}
        public string? Patrimonio {get;set;}
    }
}

Models/ErrorViewModel.cs
namespace ASPNETSEMED.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/EscolaModel.cs
namespace ASPNETSEMED.Models
{
    public class EscolaModel
    {
        public required string Id { get; set; }
        public required string Escola { get; set; }
        public string? Cnpj { get; set; }
        public string? Telefone { get; set; }
        public required string Diretor { get; set; }
        public string? Email { get; set; }
        public required string Ra { get; set; }
        public required string Bairro { get; set; }
        public float? Lat { get; set; }
        public float Lon { get; set; }
        public string? Status { get; set; }
        public string? Endereco { get; set; }
        
        public string? Ip { get; set; }
        
        public string? Circuito { get; set; }
        public string? Imagem { get; set; }


    }
}

Models/HomeModel.cs
namespace ASPNETSEMED.Models;

public class HomeModel
{   
    public string? Nome {get;set;}
    public string? Email {get;set;}
}   

Models/ImpressoraModel.cs
namespace ASPNETSEMED.Models
{
    public class ImpressoraModel
    {
        public required string Id {get;set;}
        public required string Nome {get;set;}
        public required string Setor {get;set;}

        public string? Sigla  {get;set;}

        public required string Modelo {get;set;}

        public string? Ip  {get;set;}

        public required bool Status {get;set;}

        public string? Printpage {get;set;}

        public string? Localizacao {get;set;}
    }
}



// id	nome	setor	sigla	modelo	ip	status	printpage

Controllers/AlooController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ASPNETSEMED.Models;
using ASPNETSEMED.Repositorio;

namespace ASPNETSEMED.Controllers;

public class AlooController : Controller
{
    private readonly IAlooRepositorio _alooRepositorio;

    public AlooController(IAlooRepositorio alooRepositorio)
    {
        _alooRepositorio = alooRepositorio;
    }
    public IActionResult Index()
    {

        _alooRepositorio.ListarPorConnectionNotFound();
        List<AlooModel> aloos = _alooRepositorio.ListaAloo();

        return View(aloos);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }


    public IActionResult AtualizarTabelaAloos()
    {
        _alooRepositorio.ListarPorConnectionNotFound();
        List<AlooModel> aloos = _alooRepositorio.ListaAloo();
        return PartialView("_AloosTable", aloos);
    }


}

Controllers/ContatosController.cs
using Microsoft.AspNetCore.Mvc;
using ASPNETSEMED.Models;
using ASPNETSEMED.Repositorio;

namespace ASPNETSEMED.Controllers
{
    public class ContatosController : Controller
    {
        private readonly IAnydeskRepositorio _anydeskRepositorio;

        public ContatosController(IAnydeskRepositorio anydeskRepositorio)
        {
            _anydeskRepositorio = anydeskRepositorio;
        }

        public IActionResult Index()
        {
            List<AnydeskModel> anydesks = _anydeskRepositorio.ListaAnydesk();
            return View(anydesks);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(string id)
        {
            try
            {
                AnydeskModel anydesk = _anydeskRepositorio.ListarPorId(id);
                return View(anydesk);
            }
            catch (Exception ex)
            {
                return NotFound(ex.Message);
            }
        }


        public IActionResult ApagarConfirmacao(string id)
        {
            try
            {
                AnydeskModel anydesk = _anydeskRepositorio.ListarPorId(id);
                return View(anydesk);
            }
            catch(Exception ex)
            {
                return NotFound(ex.Message);
            }
        }

        public IActionResult Apagar(string id)
        {
            _anydeskRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Criar(AnydeskModel anydesk)
        {
            _anydeskRepositorio.Adicionar(anydesk);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Alterar(AnydeskModel anydesk)
        {
            _anydeskRepositorio.Atualizar(anydesk);
            return RedirectToAction("Index");
        }
    }
}

Controllers/EscolaController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using ASPNETSEMED.Repositorio;
using ASPNETSEMED.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;

namespace ASPNETSEMED.Controllers;

public class EscolaController(IEscolaRepositorio escolaRepositorio) : Controller
{
    private readonly IEscolaRepositorio _escolaRepositorio = escolaRepositorio;

    public IActionResult Index()
    {
        List<EscolaModel> escolas = _escolaRepositorio.ListaEscola();
        var groupedEscolas = escolas.GroupBy(e => e.Ra)
                            .OrderBy(g => g.Key)
                            .ToList();

        return View(groupedEscolas);
    }

    [HttpGet]
    public IActionResult Api()
    {
        List<EscolaModel> escolas = _escolaRepositorio.ListaEscola();

        
        string json = JsonConvert.SerializeObject(escolas, new JsonSerializerSettings {
            ContractResolver = new CamelCasePropertyNamesContractResolver(),
            Formatting = Formatting.Indented,
            NullValueHandling = NullValueHandling.Ignore
        });

        
            
        return Content(json);
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ASPNETSEMED.Models;

namespace ASPNETSEMED.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ImpressoraController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using ASPNETSEMED.Repositorio;
using ASPNETSEMED.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;

namespace ASPNETSEMED.Controllers;

public class ImpressoraController(IImpressoraRepositorio impressoraRepositorio) : Controller
{
    private readonly IImpressoraRepositorio _impressoraRepositorio = impressoraRepositorio;

    public IActionResult Index()
    {
        List<ImpressoraModel> impressoras = _impressoraRepositorio.ListaImpressora();
        

        return View(impressoras);
    }

    public IActionResult Criar()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Api()
    {
        List<ImpressoraModel> impressoras = _impressoraRepositorio.ListaImpressora();

        
        string json = JsonConvert.SerializeObject(impressoras, new JsonSerializerSettings {
            ContractResolver = new CamelCasePropertyNamesContractResolver(),
            Formatting = Formatting.Indented,
            NullValueHandling = NullValueHandling.Ignore
        });

        
            
        return Content(json);
    }
}

Views/Aloo/Index.cshtml
@model List<AlooModel>

@{
    ViewData["Title"] = "Listagem Aloo";
}



<div id="aloosTable">
    <!-- Conteúdo da tabela aqui -->
    <table class="display table table-striped table-hover table-dark caption" id="example">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">DIAS</th>
                <th scope="col">ESCOLA</th>
                <th scope="col">CIRCUITO</th>
                <th scope="col">IP</th>
            </tr>
        </thead>
        <tbody>
            <!-- Linhas da tabela aqui -->
            @if (Model != null && Model.Any())
            {
                for (int i = 0; i < Model.Count; i++)
                {
                    int j = i + 1;
                    <tr>
                        <th scope="row">@j</th>
                        <td id=>
                            @{
                                var diferenca = DateTime.UtcNow - Model[i].Criacao;
                                var formatoDesejado = string.Format("{0} dias, {1} horas, {2} minutos, {3} segundos",
                                                            diferenca.Days,
                                                            diferenca.Hours,
                                                            diferenca.Minutes,
                                                            diferenca.Seconds);
                                @formatoDesejado
                            }
                        </td>
                        <td>@Model[i].Escola</td>
                        <td>@Model[i].Circuito</td>
                        <td>@Model[i].Ip</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

@section Scripts{
    <script src="~/js/views/aloo/index.js"></script>
}

Views/Aloo/_AloosTable.cshtml
@model List<AlooModel>

@{
    ViewData["Title"] = "Listagem Aloo";
}

<div id="aloosTable">
<table class="display table table-striped table-hover table-dark caption" id="example">
    <!-- Cabeçalho da tabela aqui -->
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">DIAS</th>
            <th scope="col">ESCOLA</th>
            <th scope="col">CIRCUITO</th>
            <th scope="col">IP</th>
        </tr>
    </thead>
    <tbody>
        <!-- Linhas da tabela aqui -->
        @if (Model != null && Model.Any())
        {
            for (int i = 0; i < Model.Count; i++)
            {
                int j = i + 1;
                <tr>
                    <th scope="row">@j</th>
                    <td>
                        @{
                            var diferenca = DateTime.UtcNow - Model[i].Criacao;
                            var formatoDesejado = string.Format("{0} dias, {1} horas, {2} minutos, {3} segundos",
                                                        diferenca.Days,
                                                        diferenca.Hours,
                                                        diferenca.Minutes,
                                                        diferenca.Seconds);
                            @formatoDesejado
                        }
                    </td>
                    <td>@Model[i].Escola</td>
                    <td>@Model[i].Circuito</td>
                    <td>@Model[i].Ip</td>
                </tr>
            }
        }
    </tbody>
</table>
</div>


@* <script src="~/js/views/aloo/index.js"></script> *@

Views/Contatos/ApagarConfirmacao.cshtml
@model AnydeskModel;

@{
    ViewData["Title"] = "Apagar Contato";
}

<div class="text-center">
    <h3>Deseja realmente apagar o Anydesk @Model.Id, da Escola @Model.Escola, e o Patrimônio @Model.Patrimonio</h1>
</div>


<a class="btn btn-primary btn-block" role="button" asp-controller="Contatos" asp-action="Index">Cancelar a exclusão</a>
<a class="btn btn-danger btn-block" asp-route-id="@Model.Id" asp-controller="Contatos" asp-action="Apagar" role="button">Confirmar a exclusão</a>

Views/Contatos/Criar.cshtml
@model AnydeskModel;

@{
  ViewData["Title"] = "Cadastro Anydesk";
}


<div class="text-center">
  <h1 class="display-4">Cadastrar Contato</h1>
</div>

<br>
<br>
<div class="text-center">
  <form asp-controller="Contatos" asp-action="Criar" method="post">
    <div class="mb-3">
      <label class="display-6">Anydesk</label>
      <br>
      <br>
      <input type="text" asp-for="Id" class="form-control" required>
    </div>

    <div class="mb-3">
      <label class="display-6">Escola</label>
      <br>
      <br>
      <select asp-for="Escola" class="js-example-basic-single" id="escola-select" required></select>
    </div>

    <div class="mb-3">
      <label class="display-6">Patrimônio</label>
      <br>
      <br>
      <input type="text" asp-for="Patrimonio" class="form-control" required>
    </div>

    <a class="btn btn-secondary" asp-controller="Contatos" asp-action="Index" role="button">Voltar</a>
    <button type="submit" class="btn btn-success">Cadastrar</button>
  </form>
</div>

<script>
  $(document).ready(function () {
    fetch('http://localhost:5114/Escola/Api')
        .then(response => response.json()) 
        .then(data => {
            // Agrupar os dados por 'ra'
            const groupedData = data.reduce((acc, item) => {
                if (!acc[item.ra]) {
                    acc[item.ra] = [];
                }
                acc[item.ra].push({
                    id: item.id,
                    text: item.escola
                });
                return acc;
            }, {});

            // Criar a estrutura para o select2 com optgroup
            const selectData = Object.keys(groupedData).map(ra => ({
                text: `RA ${ra}`,
                children: groupedData[ra]
            }));

            $('.js-example-basic-single').select2({
                data: selectData,
                width: '100%',
                placeholder: "Escolha uma escola",
            });
        })
        .catch(error => {
            console.error('Erro ao buscar dados da API:', error);
        });
});


</script>

Views/Contatos/Editar.cshtml
@model AnydeskModel

@{
    ViewData["Title"] = "Editar Contatos";
}

<div class="text-center">
    <h1 class="display-4">Editar Contato</h1>
</div>

<div class="text-center">
  <form asp-controller="Contatos" asp-action="Alterar" method="post">
    <div class="mb-3">
      <label  class="display-6">Anydesk</label>
      <br>
      <br>
      <input type="text" asp-for="Id" class="form-control" >
    </div>

    <div class="mb-3">
      <label  class="display-6">Escola</label>
      <br>
      <br>
      <input type="text" asp-for="Escola" class="form-control" >
    </div>
    <div class="mb-3">
      <label  class="display-6">Patrimônio</label>
      <br>
      <br>
      <input type="text" asp-for="Patrimonio" class="form-control" >
    </div>

    <a class="btn btn-secondary" asp-controller="Contatos" asp-action="Index" role="button">Voltar</a>
    <button type="submit" class="btn btn-primary btn-block">Alterar</button>
</form>

</div>

Views/Contatos/index.cshtml
@model List<AnydeskModel>

@{
    ViewData["Title"] = "Listagem Contatos";
}

<link href="~/css/views/contatos/index.css" rel="stylesheet" />



<div class="text-center">
    <h1 class="display-4">Listagem de Anydesk</h1>
    <br />
</div>


<div class="text-center">
    <table class="display table table-striped table-hover table-dark caption " id="example">
        <caption><a class="btn btn-success" role="button" asp-controller="Contatos" asp-action="Criar">Adicionar um novo
                Anydesk</a></caption>
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">ANYDESK</th>
                <th scope="col">ESCOLA</th>
                <th scope="col">PATRIMÔNIO</th>
                <th scope="col"></th>
                <th scope="col">Teste</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                for (int i = 0; i < Model.Count; i++)
                {
                    int j = i + 1;
                    <tr>
                        <th scope="row">@j</th>
                        <td>@Model[i].Id</td>
                        <td>@Model[i].Escola</td>
                        <td>@Model[i].Patrimonio</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a type="button" class="btn btn-primary" asp-route-id="@Model[i].Id" asp-controller="Contatos"
                                    asp-action="Editar" role="button">Editar</a>
                                <a type="button" class="btn btn-danger" asp-route-id="@Model[i].Id" asp-controller="Contatos"
                                    asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                        <td>
                            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                Launch demo modal
                            </button>

                        </td>

                    </tr>
                }
            }
        </tbody>
    </table>


    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        
        <h5 class="modal-title" id="exampleModalLabel">Editar Anydesk</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        OI
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
    <br>


    <script defer
        src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
    <script defer src="https://cdn.datatables.net/2.0.7/js/dataTables.js"></script>
    <script defer src="https://cdn.datatables.net/2.0.7/js/dataTables.bootstrap5.js"></script>
    <script defer src="~/js/views/contatos/index.js"></script>

</div>

Views/Escola/Api.cshtml
@model EscolaModel;

@{
    ViewData["Title"] = "Api Escola";
}

Views/Escola/Index.cshtml
@model List<IGrouping<string, EscolaModel>>

@{
    ViewData["Title"] = "Escola";
}

<link rel="stylesheet" href="~/css/views/escola/index.css">


<nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark ">
    <div class="container-fluid">
        <img src="~/icons/views/escola/school_icon.svg" alt="Logo" width="35" height="38" class="d-inline-block align-text-top mx-3">
        <a class="navbar-brand" href="#">Escolas da Rede Municipal de Maceió</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" href="#" >Adicionar Escola</a>
                @* <a class="nav-link" href="#">Features</a>
                <a class="nav-link" href="#">Pricing</a>
                <a class="nav-link disabled" aria-disabled="true">Disabled</a> *@
            </div>
        </div>
    </div>
    <form class="d-flex me-2">
        <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle " type="button" data-bs-toggle="dropdown" aria-expanded="false">Auditoria</button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Auditar Ip´s</a></li>
                            <li><a class="dropdown-item" asp-controller="Aloo" asp-action="Index">Aloo</a></li>
                        </ul>
                </div>
        <input id="searchInput" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-custom-color" type="submit">Search</button>
    </form>
</nav>

<div class="container" id="cardContainer">
    @foreach (var group in Model)
    {
        if (group.Key != "1")
        {
            <br>
        }
        <h2 class="text-white"><img src="~/icons/views/escola/ra_icon.svg" alt="Logo" width="48" height="36" class="mx-2">Região Administrativa @group.Key.</h2>
        <br>
        <div class="row g-3">
            @foreach (var escola in group)
            {
                <div class="col-md-4 card-item" data-escola="@escola.Escola">
                    <div class="card">
                        <img class="bd-placeholder-img card-img-top"  height="180" src="~/fotos/escola/@escola.Imagem">
                        <div class="card-body">
                            <div class="text-center">
                                <h5 class="card-title">@escola.Escola</h5>
                                <p class="card-text">@escola.Endereco</p>
                            </div>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <div class="text-center">Diretora: @escola.Diretor</div>
                            </li>
                            <li class="list-group-item">
                                <div class="text-center">Contato: @escola.Telefone</div>
                            </li>
                            <li class="list-group-item">
                                <div class="text-center">Bairro: @escola.Bairro</div>
                            </li>
                            <li class="list-group-item">
                                <div class="text-center">Circuito: @escola.Circuito</div>
                            </li>
                           <li class="list-group-item d-flex align-items-center justify-content-center">
                                @if(escola.Ip != null)
                                {
                                    <div class="text-center">IP: @escola.Ip</div>
                                    <button type="button" class="btn-ping btn" data-bs-toggle="modal" data-bs-target="#exampleModal"><img src="~/css/Views/Escola/ping.svg" alt=""></button>
                                } else{
                                    <div class="text-center">IP Nulo</div>
                                }
                            </li>

                        </ul>
                        <a href="#" class="btn btn-custom-color">Ver Detalhes <img src="~/icons/search.svg" alt="Logo" width="23" height="25" class="d-inline-block align-text-top mx-1 bs-white"></a>
                    </div>
                </div>
            }
        </div>
    }
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="~/js/views/escola/index.js"></script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Impressora/Criar.cshtml
@model ImpressoraModel;

@{
  ViewData["Title"] = "Cadastro Anydesk";
}

<link href="~/css/views/impressora/criar.css" rel="stylesheet" />

<div class="text-center">
  <h1 class="display-4">Cadastrar Impressora</h1>
</div>

<br>

<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="~/fotos/impressora/cadastro_impressora.png" class="img-fluid rounded-start" alt="...">
    </div>

    <div class="col-md-8">

      <div class="card-body" style="margin-left: 10px;">
        <div class="container px-1">
          <div class="row gy-4">

            <div class="col-6">
              <input>
            </div>

            <div class="col-6">

              <div class="p-3 border">Custom column padding

              </div>
            </div>

            <div class="col-6">
              <div class="p-3 border">Custom column padding</div>
            </div>

            <div class="col-6">
              <div class="p-3 border">Custom column padding</div>
            </div>

            <div class="col-6">
              <div class="p-3 border">Custom column padding</div>
            </div>

            <div class="col-6">
              <div class="p-3 border">Custom column padding</div>
            </div>

            <div class="col-6">
              <div class="button-row mt-auto">
            <a class="btn-back btn btn-secondary"  asp-controller="Contatos" asp-action="Index" role="button">Voltar</a>
            <button type="submit" class="btn-singup btn btn-success">Cadastrar</button>
            </div>
            </div>
            

          </div>
        </div>
      </div>
    </div>
  </div>
</div>



@* <div class="text-center">
<form asp-controller="Impressora" asp-action="Criar" method="post">
<div class="mb-3">
<label class="display-6">ID</label>
<br>
<br>
<input type="text" asp-for="Id" class="form-control" required>
</div>

<div class="mb-3">
<label class="display-6">Nome</label>
<br>
<br>
<input type="text" asp-for="Nome" class="form-control" required>
</div>

<div class="mb-3">
<label class="display-6">Setor</label>
<br>
<br>
<input type="text" asp-for="Setor" class="form-control" required>
</div>

<div class="mb-3">
<label class="display-6">Sigla</label>
<br>
<br>
<input type="text" asp-for="Sigla" class="form-control">
</div>

<div class="mb-3">
<label class="display-6">Modelo</label>
<br>
<br>
<input type="text" asp-for="Modelo" class="form-control" required>
</div>

<div class="mb-3">
<label class="display-6">IP</label>
<br>
<br>
<input type="text" asp-for="Ip" class="form-control">
</div>

<div class="mb-3">
<label class="display-6">PrintPage</label>
<br>
<br>
<input type="text" asp-for="Printpage" class="form-control">
</div>

<div class="mb-3">
<label class="display-6">Status</label>
<br>
<br>
<input type="text" asp-for="Status" class="form-control" required>
</div>

<a class="btn btn-secondary" asp-controller="Contatos" asp-action="Index" role="button">Voltar</a>
<button type="submit" class="btn btn-success">Cadastrar</button>
</form>
</div> *@

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TesteMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script defer src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.7/js/dataTables.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TesteMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Pagina Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Escola" asp-action="Index">Escola</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contatos" asp-action="Index">Anydesk</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Impressora" asp-action="Index">Impressora</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color: white;">
        <div class="container">
            &copy; 2024 - TesteMVC
        </div>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>